version: "3"

services:
  api:
    image: bsale-api
    container_name: bsale-api
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    environment:
      NODE_ENV: development
      CORS_ORIGIN_WHITELIST: http://localhost:3000
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
